version: '2'

services:
  web:
    build: .
    environment:
      PORT: 8080
    command: 'bash -c ''/go/bin/arc-api-proxy'''
    working_dir: /go/src/arc-api-proxy
    ports:
      - '8080'
    restart: always
  lb:
    image: dockercloud/haproxy
    links:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
    restart: always